version: "3.9"

services:
  postgres:
    image: postgis/postgis:16-3.4   # PostgreSQL 16 + PostGIS 3.4
    container_name: postgis_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gisdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d gisdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
